spring:
  datasource:
    url: jdbc:mysql://124.220.80.204:3306/se2?user=root&password=041015&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mikumifa.wms.entity.dto
  configuration:
    map-underscore-to-camel-case: true


